### ISSUE TITLE
Components architecture issue 

### ISSUE THREAD

**Issue by ChechaValerii** [toliankir/onix_express#2]
Let's try to move all this logic to the User component 
In my opinion UserView component is a duplicate from User component
(service, validation the same). 

https://github.com/toliankir/onix_express/blob/e473303cc82b46f2c48b7518b8c7f706462cadb2/src/components/UserView/index.js#L1

**Comment by toliankir** [comment]
I want save REST api functional.

Can I adds one more router file to User components folder for frontend routes?

Maybe, better add one more Router() object to old router.js file and exports two router object from it. One of router object will be handle api routes, another handle frontend requests.

Sorry for my English.

**Comment by toliankir** [comment]
Merge Components to one

**Comment by ChechaValerii** [comment]
I think the better create 1 router with more smart logic. For example
/v1/users 
'get /v1/users' - show all
'post /v1/users' - create many (bulk)
'delete /v1/users  - remove many'

/v1/users/user
 'get /v1/users/user' - show one
 'post /v1/users/user/delete' - for delete one (post because form do not have method delete)
 'post /v1/users/user/create' - for creat one
...etc

**Comment by toliankir** [comment]
Ok. I merge all routes to one object in this component.

You have written:
_for delete one (post because form do not have method delete)_
But I have added "method-override" library. This middleware allows use 'PUT', "DELETE' ... methods in html forms, all what I need it is add hidden filed '_method' in my html form. Is this right disidion?
